config/routes.rb
Blog::Application.routes.draw do

  resources :posts do
    resources :comments, :only => [:create, :destroy]
  end

  root :to => 'posts#index'

match '/home' => 'pages#home'
match '/about' => 'pages#about'
match '/contact' => 'pages#contact'
controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :body, :name
  validates_presence_of :body, :name
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title
  has_many :comments, :order => "created_at DESC"
  validates_presence_of :body, :title


end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username

  validates :username, presence: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

helper_method :current_user, :logged_in?

private


  def current_user
    @current ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
    flash[:error] = "You can't do that!"
    redirect_to root_path
    end
  end

 end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :admin_user, :only => [:destroy]

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create!(params[:comment])
    redirect_to @post
  end

  def destroy
  	@post = Post.find(params[:post_id])
  	@comment = Comment.find(params[:id])
  	@comment.destroy
  	redirect_to posts_path(@post)
  end
end


def admin_user
  authenticate
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :require_user, only: [:new, :create, :update, :edit, :destroy]


  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.paginate :page => params[:page], :per_page => 5, :order => "created_at DESC"


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
      format.atom
    end
  end

  def feed
    @posts = Post.all(:select => "title, author, id, content, posted_at", :order => "posted_at DESC", :limit => 20)

    respond_to do |format|
      format.html
      format.rss { render :layout => false } #index.rss.builder
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new; end

  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "You logged in!"
    else
      flash[:alert] = "There's something wrong with your username or password"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
  <p>
  	<strong><%= comment.name %></strong> says:<br />
  	<%= h(comment.body) %>
  	<% if logged_in? %>
      <%= link_to 'Delete', [@post, comment], :method => :delete, :confirm => 'Are you sure?' %><br />
    <% end %>
  	<br/><strong>Posted <%= time_ago_in_words(comment.created_at) %> ago<br/></strong>
  </p>

<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :post %><br />
    <%= f.text_field :post %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Body</th>
    <th>Post</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.name %></td>
    <td><%= comment.body %></td>
    <td><%= comment.post %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @comment.name %>
</p>

<p>
  <b>Body:</b>
  <%= @comment.body %>
</p>

<p>
  <b>Post:</b>
  <%= @comment.post %> 
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>
<%= link_to('new comment',new_post_path) %>
<%= link_to 'Delete', @post, :method => :delete, :confirm => 'Are you sure?' %> |

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Josh's Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%-#= auto_discovery_link_tag(:atom, {action: "feed"}, {title: "RSS Feed"}) %>
</head>
<body>
<div id="header">
<div class="links">
<%= link_to "Home", root_path %> |
<%= link_to "About", about_path  %> |
<%= link_to "Contact", contact_path %>
</div>
</div>

<div id="page"><%= yield %></div>


</body>
</html>

app/views/pages/about.erb
<h3 class="static">
  <div>
    Two years ago I didn't even know there was such a thing as a programming language. Now, after nine months of studying web development on my own (with some help from friends), I've recently begun a series of classes in Rails development.
  </div>
  <br/>
  <div>
    This blog will serve as a way for me to catalog what I learn. In a way, it will function more like a journal. I don't expect very much interaction or discussion to take place, but these posts will serve as a personal repository of information, and as a means of personal encouragement (who doesn't like to look back on their work and see how much they've learned).
  </div>

</h3>

app/views/pages/contact.erb
<h3 class="static">Just leave a comment for now.</h3>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<%= div_for post do%>
  <h2 class="titles"><%= link_to_unless_current h(post.title), post %></h2>
  <%=h simple_format truncate(post.body, :length => 1000, :separator => ' ', :omission => "...Read More") %>
  <h5>Posted <%= time_ago_in_words(post.created_at) %> ago </br>
      <%= post.comments.size %> Comments
  </h5>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div id="title"><h1 id="title">Riding on Rails</h1></div>
<h3 id="subtitle">My Journey into Web Development</h3>



<%= render :partial => @posts %>


<%= will_paginate @posts %><br/>
<% if logged_in? %>
<%= link_to 'New Post', new_post_path %>
<div style="text-align: right"><%= link_to 'logout', logout_path %></div>
<% else %>
<div style="text-align: right"><%= link_to 'Login', login_path %></div>
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
 <p id="notice"><%= notice %></p>

<%= div_for @post do%>
  <h2 class="titles"><%= link_to_unless_current h(@post.title), @post %></h2>
  <%=h simple_format word_wrap(@post.body, :line_width => 130) %>
  <h5>Posted <%= time_ago_in_words(@post.created_at) %> ago </br>
      <%= @post.comments.size %> Comments
  </h5>
<% end %>

<p>
  <% if logged_in? %>
    <%= link_to 'Edit', edit_post_path(@post) %> |
    <%= link_to 'Delete', @post, :method => :delete, :confirm => "Are you sure?" %>
  <% end %>


<h2 class="titles">Comments</h2>
<div id="comments">
	<%= render :partial => @post.comments %>
</div>


<%= form_for [@post, Comment.new] do |f| %>
  <p>
  	<%= f.label :name, "Name" %><br />
  	<%= f.text_field :name%>
  </p>


  <p>
  	<%= f.label :body, "New Comment" %><br />
  	<%= f.text_area :body %>
  </p>
  <p><%= f.submit "Add Comment" %></p>
<% end %>